"""removes is_active flag from vote

Revision ID: 1fd9dd790eea
Revises: 66661ab77942
Create Date: 2026-01-23 12:42:02.934745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fd9dd790eea'
down_revision: Union[str, None] = '66661ab77942'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('votes', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('is_active', sa.BOOLEAN(), nullable=False))
    # ### end Alembic commands ###
